### ISSUE TITLE
Allow selection of output folder

### ISSUE THREAD

**Issue by genomewalker** [maxibor/pydamage#18]
Hi @maxibor 
a small issue, would it be possible to get the `-o` option from previous versions back for `analyze` and `filter`?

Many thanks
Antonio

**Comment by maxibor** [comment]
Hi @genomewalker ,
It wasn't removed, but moved.
Now that PyDamage has subcommands, the commong options, such as `--ouptput` were moved to the main command, i.e:
`pydamage --output analyze yourfile.bam`
