### ISSUE TITLE
Analyzing not so ancient DNA?

### ISSUE THREAD

**Issue by Anto007** [maxibor/pydamage#21]
Hi,

Perhaps this is a rookie question from being an outsider to the aDNA field: Will pydamage show any discrimination between old and new DNA if the source material is only a decade old? I intend to analyze shotgun metagenomic data that is derived from a (long-dead) marine sample that had living cells perhaps 10 years ago and was in the sea environment for that long. I have absolutely no idea how the cytosine deamination rates are like for DNA out in the sea but it would be great if I could separate the original (older) biological sample from the relatively recent biological contaminants. Do you think it will be silly to expect pydamage to be of any help in this regard?

**Comment by maxibor** [comment]
If there is deamination like damage, PyDamage can help.
