### ISSUE TITLE
Question for understanding

### ISSUE THREAD

**Issue by Anto007** [maxibor/pydamage#22]
Hi,

I have a quick question for understanding: I ran `pydamage analyze mymetagenome.sorted.bam` and got no `pydamage_results.csv` file written to the `pydamage_results` directory. The job seems to have finished successfully as there were no errors shown on the console (`193320 contig(s) successfully analyzed by Pydamage`). Does this mean that none of my metagenomic contigs were having signs of C-T damage? This would be my expected result here but I just wanted to be doubly sure of my interpretation. Thanks.

P.S. My bam file was generated using only metagenomic contigs > 1000 bp length

**Comment by maxibor** [comment]
Hey @Anto007 ,
Did any read align to your contigs ? PyDamage relies on the header of the `bam` file to compute the number of contigs, but if there are no aligned segments, then the results will be empty.

**Comment by Anto007** [comment]
Thanks for your response @maxibor. Below was the output from bowtie2 at the bam file (size=20GB) generation step. 

```
246166817 reads; of these:
  246166817 (100.00%) were paired; of these:
    40484394 (16.45%) aligned concordantly 0 times
    187737929 (76.26%) aligned concordantly exactly 1 time
    17944494 (7.29%) aligned concordantly >1 times
    ----
    40484394 pairs aligned concordantly 0 times; of these:
      13004449 (32.12%) aligned discordantly 1 time
    ----
    27479945 pairs aligned 0 times concordantly or discordantly; of these:
      54959890 mates make up the pairs; of these:
        43397919 (78.96%) aligned 0 times
        6272457 (11.41%) aligned exactly 1 time
        5289514 (9.62%) aligned >1 times
91.19% overall alignment rate
[bam_sort_core] merging from 210 files and 1 in-memory blocks...
```

and below are the command-lines that I had used

```
bowtie2-build metagenome.fasta metagenome
bowtie2 -x metagenome -1 ReadA_R1.fastq.gz -2 ReadA_R2.fastq.gz --very-sensitive -N 1 | samtools view -S -b -F 4 - | samtools sort - > metagenome.sorted.bam
samtools index metagenome.sorted.bam
```

**Comment by Anto007** [comment]
Btw, the same reads had been used to build this metagenome assembly fasta file on MEGAHIT

**Comment by maxibor** [comment]
Could you share a subsample of your aligned data @Anto007 ?

You can use samtools to do so: 

```
samtools view -bs 42.1 in.bam > subsampled.bam
```

This will subsample 10 percent mapped reads with 42 as the seed for the random number generator.

**Comment by Anto007** [comment]
Many thanks for your response @maxibor; I've now emailed you a link to download the subsampled bam file

**Comment by maxibor** [comment]
Hi @Anto007 ,
Unfortunately, I wasn't able to reproduce your issue, as PyDamage ran fine on the data you sent me:

To speed up the test, I only ran the PyDamage analysis on two contigs from the file you sent me:

```bash
$ samtools view -b subsampled.bam k141_223191_flag=0_multi=30.9766_len=28327 k141_819141_flag=0_multi=52.9744_len=18454 > subsampled_2.bam
$ samtools sort subsampled_2.bam > subsampled_2.sorted.bam
$ samtools index subsampled_2.sorted.bam
$ bamAlignCleaner -o subsampled_2.sorted.cleaned.bam subsampled_2.sorted.bam
$ samtools index subsampled_2.sorted.cleaned.bam
$ pydamage analyze --plot subsampled_2.sorted.cleaned.bam
```

This works fine and generates the pydamage_results table and plots without any issues
