### ISSUE TITLE
what is file pydamage_filtered_results.csv？

### ISSUE THREAD

**Issue by timeresistance1996** [maxibor/pydamage#26]
Thank you for your codes.

I received a pydamage_filtered_results.csv result with no contig exit. Is the pydamage_filtered_results.csv file after ‘pydamage filter’ containing sequences that need to be filtered or filtered ancient sequences?

**Comment by maxibor** [comment]
Hi @timeresistance1996 ,
The typical workflow is to use `pydamage analyze` and then `pydamage filter` if you want to keep only the contigs showing signs of ancient DNA damage.

**Comment by timeresistance1996** [comment]
Yes, I successfully ran 'pydamage analyze contig.bam'. But after 'pydamage filter -t 0 pydamage_results/pydamage_results.csv', only headers were generated in the 'pydamage_filtered_results.csv'

",reference,predicted_accuracy,null_model_p0,null_model_p0_stdev,damage_model_p,damage_model_p_stdev,damage_model_pmin,damage_model_pmin_stdev,damage_model_pmax,damage_model_pmax_stdev,pvalue,qvalue,RMSE,nb_reads_aligned,coverage,reflen,CtoT-0,CtoT-1,CtoT-2,CtoT-3,CtoT-4,CtoT-5,CtoT-6,CtoT-7,CtoT-8,CtoT-9,CtoT-10,CtoT-11,CtoT-12,CtoT-13,CtoT-14,CtoT-15,CtoT-16,CtoT-17,CtoT-18,CtoT-19"

no contig is found in this file.

Does this mean that no ancient DNA damage was detected?

**Comment by maxibor** [comment]
Sounds like it

**Comment by timeresistance1996** [comment]
I understand, thank you for your response.
