### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by amycthorpe** [maxibor/pydamage#28]
Hi

I've run pydamage on multiple samples, and I'm trying to understand which variable indicates the level of damage in my samples. I'm currently using `damage_model_pmax` from those with `qvalue` < 0.05 but should I be using `damage_model_p` or `damage_model_pmin` or other variables?

Also, is there a threshold to define whether a sample has DNA damage or not?

Thank you
Amy

**Comment by maxibor** [comment]
Hey @amycthorpe ,
Hopefully this helps !
![reference](https://github.com/user-attachments/assets/8bff79d6-eac9-4295-bc66-ed74bad660a7)
